USE [master]
GO
/****** Object:  Database [Appointment_R0.1]    Script Date: 24/5/2021 9:01:31 AM ******/
CREATE DATABASE [Appointment_R0.1]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Appointment_R0.1', FILENAME = N'/var/opt/mssql/data/Appointment_R0.1.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Appointment_R0.1_log', FILENAME = N'/var/opt/mssql/log/Appointment_R0.1_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [Appointment_R0.1] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Appointment_R0.1].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Appointment_R0.1] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Appointment_R0.1] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Appointment_R0.1] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Appointment_R0.1] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Appointment_R0.1] SET ARITHABORT OFF 
GO
ALTER DATABASE [Appointment_R0.1] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Appointment_R0.1] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Appointment_R0.1] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Appointment_R0.1] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Appointment_R0.1] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Appointment_R0.1] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Appointment_R0.1] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Appointment_R0.1] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Appointment_R0.1] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Appointment_R0.1] SET  ENABLE_BROKER 
GO
ALTER DATABASE [Appointment_R0.1] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Appointment_R0.1] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Appointment_R0.1] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Appointment_R0.1] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Appointment_R0.1] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Appointment_R0.1] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [Appointment_R0.1] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Appointment_R0.1] SET RECOVERY FULL 
GO
ALTER DATABASE [Appointment_R0.1] SET  MULTI_USER 
GO
ALTER DATABASE [Appointment_R0.1] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Appointment_R0.1] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Appointment_R0.1] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Appointment_R0.1] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Appointment_R0.1] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'Appointment_R0.1', N'ON'
GO
ALTER DATABASE [Appointment_R0.1] SET QUERY_STORE = OFF
GO
USE [Appointment_R0.1]
GO
/****** Object:  Schema [AppointmentMain]    Script Date: 24/5/2021 9:01:31 AM ******/
CREATE SCHEMA [AppointmentMain]
GO
/****** Object:  Schema [Tenant_001]    Script Date: 24/5/2021 9:01:31 AM ******/
CREATE SCHEMA [Tenant_001]
GO